# Namespace-Restricted RBAC for Podboard
# This configuration limits pod deletion to the deployment namespace only
# Recommended for most use cases

apiVersion: v1
kind: ServiceAccount
metadata:
  name: podboard
  namespace: default
---
# Role for namespace-specific pod operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podboard-namespace
  namespace: default
rules:
# Core pod monitoring permissions
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Pod deletion permission (restricted to this namespace)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
# ClusterRole for cluster-wide read-only operations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podboard-cluster-readonly
rules:
# Namespace discovery for filtering
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
# Read-only pod access across namespaces for monitoring
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
# Bind namespace-specific role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podboard-namespace
  namespace: default
subjects:
- kind: ServiceAccount
  name: podboard
  namespace: default
roleRef:
  kind: Role
  name: podboard-namespace
  apiGroup: rbac.authorization.k8s.io
---
# Bind cluster-wide read-only role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podboard-cluster-readonly
subjects:
- kind: ServiceAccount
  name: podboard
  namespace: default
roleRef:
  kind: ClusterRole
  name: podboard-cluster-readonly
  apiGroup: rbac.authorization.k8s.io