apiVersion: v1
kind: Service
metadata:
  name: podboard
  namespace: default
  labels:
    app: podboard
    component: dashboard
spec:
  type: ClusterIP
  ports:
  - port: 9999
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: podboard
---
# Optional: Ingress for external access
# Uncomment and configure according to your ingress controller
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: podboard
#   namespace: default
#   labels:
#     app: podboard
#   annotations:
#     # nginx.ingress.kubernetes.io/rewrite-target: /
#     # cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   # tls:
#   # - hosts:
#   #   - podboard.example.com
#   #   secretName: podboard-tls
#   rules:
#   - host: podboard.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: podboard
#             port:
#               number: 9999